version: "3"
# networks: 
#   app:
#     driver: bridge
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER_ID}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./Database/:/docker-entrypoint-initdb.d/

  server:
    # networks:
    #   - app
    build:
      context: .
    container_name: server
    # links: 
    #   - "postgres:"
    ports:
      - "3001:3001"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
    restart: always