version: "3"
networks: 
  app:
    driver: bridge
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres12
      POSTGRES_DB: server_db
  server:
    networks:
      - app
    build:
      context: .
    container_name: server
    ports:
      - '3001:3001'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
    restart: always